[package]
name = "reginald-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { version = "0.4.27", features = ["max_level_trace", "release_max_level_info"] }
uefi = { version = "0.34.1", features = ["logger", "panic_handler"] }
